name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-website:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-website:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: consist-advantages-accomplished-shame.trycloudflare.com
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          proxy_host: consist-advantages-accomplished-shame.trycloudflare.com
          proxy_port: 443
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerce-website:latest
            docker stop ecommerce-website || true
            docker rm ecommerce-website || true
            docker run -d -p 80:80 --name ecommerce-website ${{ secrets.DOCKER_USERNAME }}/ecommerce-website:latest
